# Header
menu:
  Home: /
  Events: /categories/Events
  Archives: /archives/
  Contact: /#contact
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Integrations
disqus_shortname: kde-indonesia
google_analytics: 
swiftype_install_key:

# Social
social:
  github: https://github.com/kdeid
  twitter: https://twitter.com/kde_id
  facebook: https://www.facebook.com/groups/kde.id/
  telegram: https://t.me/kdeid
  rss: atom.xml
  # linkedin: 
  # stackoverflow:

# Miscellaneous
color_scheme: blue   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.png # path from root of hexo site
#twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: kde_id # twitter username without the app
default_author: KDE Indonesia

#about: Lorem ipsum dolor sit amet, dolore eiusmod quis tempor incididunt ut et dolore Ut veniam unde nostrudlaboris.
#phone: 
#email: 
#address_1:
#address_2:
#address_3:
#skype:
#lat:
#long:
